version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout

      - run:
          name: Docker Build
          command: |
            TAG="${CIRCLE_BUILD_NUM}"
            docker build --compress -t jgcl88/alpine-nginx-php:ci-$TAG .

      - run:
          name: Docker Images
          command: |
            docker images

      - run:
          name: Docker Login
          command: docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD

      - run:
          name: Docker send image to dockerhub
          command: |
            TAG="${CIRCLE_BUILD_NUM}"
            docker push jgcl88/alpine-nginx-php:ci-$TAG

      - run:
          name: Latest tag
          command: |
            TAG="${CIRCLE_BUILD_NUM}"
            docker tag jgcl88/alpine-nginx-php:ci-$TAG jgcl88/alpine-nginx-php:latest-ci
            docker push jgcl88/alpine-nginx-php:latest-ci