version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout

      - run:
        name: Docker Build
        command: |
          TAG="0.1.${CIRCLE_BUILD_NUM}"
          docker build -t jgcl88/php71databases:$TAG .

      - run:
        name: Docker Images
        command: |
          docker images

      - run:
          name: Docker Login
          command: docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD

      - run:
          name: Docker send image to dockerhub
          command: |
            TAG="0.1.${CIRCLE_BUILD_NUM}"
            docker push jgcl88/alpine-nginx-php:$TAG